"""Constants for Irrigation Manager."""

from typing import Final

DOMAIN: Final = "irrigation_manager"
INTEGRATION_NAME: Final = "Irrigation Manager"

CONF_MAIN_VALVE: Final = "main_valve"
CONF_WATER_METER: Final = "water_meter"
CONF_METER_MAX_AGE_SECONDS: Final = "meter_max_age_seconds"
CONF_FLOW_SENSOR: Final = "flow_sensor"
CONF_FLOW_MAX_AGE_SECONDS: Final = "flow_max_age_seconds"
CONF_LEAK_MONITORING: Final = "leak_monitoring"
CONF_LEAK_FLOW_THRESHOLD: Final = "leak_flow_threshold"
CONF_LEAK_DURATION_SECONDS: Final = "leak_duration_seconds"
CONF_WEATHER_ENTITY: Final = "weather_entity"
CONF_FROST_ENTITY: Final = "frost_entity"
CONF_FROST_THRESHOLD: Final = "frost_threshold"
CONF_RAIN_STOP_ENTITY: Final = "rain_stop_entity"
CONF_RAIN_STOP_THRESHOLD: Final = "rain_stop_threshold"
CONF_WEATHER_MAX_AGE_SECONDS: Final = "weather_max_age_seconds"
CONF_WEATHER_FAILURE_POLICY: Final = "weather_failure_policy"
CONF_INSTALLATION_MAX_DELIVERY_RUNTIME: Final = "installation_max_delivery_runtime"
CONF_INSTALLATION_MAX_OPERATION_LIFETIME: Final = "installation_max_operation_lifetime"
CONF_ACTUATOR_TRANSITION_GRACE_SECONDS: Final = "actuator_transition_grace_seconds"
CONF_NOTIFY_ENTITIES: Final = "notify_entities"
CONF_ZONE_VALVE: Final = "zone_valve"
CONF_DEFAULT_DURATION: Final = "default_duration"
CONF_MIN_FLOW: Final = "min_flow"
CONF_MAX_FLOW: Final = "max_flow"
CONF_FLOW_GRACE_SECONDS: Final = "flow_grace_seconds"
CONF_METER_FAILURE_STRATEGY: Final = "meter_failure_strategy"
CONF_MAX_DOSE_AMOUNT: Final = "max_dose_amount"
CONF_MAX_DOSE_DURATION: Final = "max_dose_duration"
CONF_SOAK_DURATION: Final = "soak_duration"
CONF_AUTOMATION_ENABLED: Final = "automation_enabled"
CONF_WATERING_MODE: Final = "watering_mode"
CONF_AREA_M2: Final = "area_m2"
CONF_APPLICATION_EFFICIENCY: Final = "application_efficiency"
CONF_CROP_FACTOR: Final = "crop_factor"
CONF_RAIN_FACTOR: Final = "rain_factor"
CONF_MAXIMUM_DEFICIT_MM: Final = "maximum_deficit_mm"
CONF_MINIMUM_INTERVAL_DAYS: Final = "minimum_interval_days"
CONF_MAXIMUM_INTERVAL_DAYS: Final = "maximum_interval_days"
CONF_MINIMUM_TRIGGER_LITERS: Final = "minimum_trigger_liters"
CONF_MANDATORY_AMOUNT_LITERS: Final = "mandatory_amount_liters"
CONF_MINIMUM_EFFECTIVE_LITERS: Final = "minimum_effective_liters"
CONF_MAXIMUM_TARGET_LITERS: Final = "maximum_target_liters"
CONF_AUTOMATIC_MAX_DURATION: Final = "automatic_max_duration"
CONF_MAX_DELIVERY_RUNTIME: Final = "max_delivery_runtime"
CONF_MAX_OPERATION_LIFETIME: Final = "max_operation_lifetime"
CONF_ZONE_PRIORITY: Final = "zone_priority"
CONF_WATERING_WINDOWS: Final = "watering_windows"
CONF_MAINTENANCE_MAX_DURATION: Final = "maintenance_max_duration"
CONF_MAINTENANCE_CONFIRMATION_INTERVAL: Final = "maintenance_confirmation_interval"
CONF_CALIBRATION_SETTLE_SECONDS: Final = "calibration_settle_seconds"

WATERING_MODE_DEMAND: Final = "demand"
WATERING_MODE_MINIMUM: Final = "minimum"

METER_FAILURE_ABORT: Final = "abort"
METER_FAILURE_ESTIMATED_TIME_FALLBACK: Final = "estimated_time_fallback"
WEATHER_FAILURE_FAIL_SAFE: Final = "fail_safe"

SUBENTRY_TYPE_ZONE: Final = "zone"

EVENT_IRRIGATION_MANAGER: Final = "irrigation_manager_event"
EXPORT_SCHEMA_VERSION: Final = 1
