import type { HassEntity, HomeAssistant } from "./types";

const messages = {
  en: {
    overview: "Irrigation overview",
    zone: "Irrigation zone",
    unavailable: "Unavailable",
    unknown: "Unknown",
    missing: "Entity not found",
    select_installation: "Select an irrigation installation.",
    select_zone: "Select an irrigation zone.",
    invalid_installation_anchor: "Select the irrigation installation status entity.",
    invalid_zone_anchor: "Select the irrigation zone status entity.",
    idle: "Idle",
    watering: "Watering",
    soaking: "Soaking",
    error: "Error",
    safety_lock: "Safety lock",
    emergency_stop: "Emergency stop",
    needs_reconfiguration: "Reconfiguration required",
    disabled: "Disabled",
    automatic_disabled: "Active, automatic irrigation disabled",
    installation_disabled: "Installation disabled",
    on: "On",
    off: "Off",
    pending: "Open requests",
    next: "Next irrigation",
    emergency: "Emergency stop",
    action_failed: "Action failed",
    configuration_error: "The selected entity does not expose the identifiers required by this action.",
    locked: "Locked",
    unlocked: "Ready",
    target: "Target",
    amount: "Amount",
    duration: "Duration",
    hard_limit: "Maximum duration",
    liters: "L",
    seconds: "s",
    maximum: "Maximum",
    start: "Start now",
    invalid_target: "Enter a value greater than zero.",
    invalid_duration: "Enter a valid positive duration.",
    hard_limit_required: "Enter a valid positive maximum duration.",
    status: "Status",
    amount_mode: "Amount controlled",
    duration_mode: "Time controlled",
    installation: "Irrigation installation",
    physical_meter: "Physical meter",
    next_zone: "Next zone",
    expected_start: "Expected start",
    runtime_today: "Runtime today",
    runtime_month: "Runtime this month",
    water_today: "Measured water today",
    water_month: "Measured water this month",
    irrigation_orders: "Irrigation orders",
    no_open_orders: "No open irrigation orders",
    close: "Close",
    loading: "Loading...",
    manual_water: "Water manually",
    show_history: "Show history",
    stop_watering: "Stop irrigation",
    confirm_stop_watering: "Stop the active irrigation for this zone?",
    active_execution_choice: "Another irrigation execution is active",
    stop_active_start_now: "Stop active execution and start now",
    finish_then_priority: "Finish active execution and run next",
    irrigation_history: "Irrigation history",
    source: "Source",
    result: "Result",
    all: "All",
    manual: "Manual",
    automatic: "Automatic",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
    runtime: "Runtime",
    water_amount: "Water amount",
    pagination: "History pagination",
    page: "Page",
    of: "of",
    entries: "Entries",
    previous: "Previous",
    next_page: "Next",
    date: "Date",
    today: "Today",
    previous_day: "Previous day",
    next_day: "Next day",
    no_orders_for_day: "No open irrigation orders for this day.",
    next_orders_on: "Show next orders on",
    partial_irrigation: "Partial irrigation",
    portion: "Portion",
    portions: "Portions",
    remaining_target: "Remaining target",
    next_portion: "Continue from",
    latest_safe_start: "Latest safe start",
  },
  de: {
    overview: "Bewässerungsübersicht",
    zone: "Bewässerungszone",
    unavailable: "Nicht verfügbar",
    unknown: "Unbekannt",
    missing: "Entity nicht gefunden",
    select_installation: "Bewässerungsanlage auswählen.",
    select_zone: "Bewässerungszone auswählen.",
    invalid_installation_anchor: "Die Status-Entity der Bewässerungsanlage auswählen.",
    invalid_zone_anchor: "Die Status-Entity der Bewässerungszone auswählen.",
    idle: "Bereit",
    watering: "Bewässerung läuft",
    soaking: "Sickerpause",
    error: "Fehler",
    safety_lock: "Sicherheitssperre",
    emergency_stop: "Not-Aus aktiv",
    needs_reconfiguration: "Neukonfiguration erforderlich",
    disabled: "Deaktiviert",
    automatic_disabled: "Aktiv, Automatik deaktiviert",
    installation_disabled: "Anlage deaktiviert",
    on: "Ein",
    off: "Aus",
    pending: "Offene Aufträge",
    next: "Nächste Bewässerung",
    emergency: "Not-Aus",
    action_failed: "Aktion fehlgeschlagen",
    configuration_error: "Die gewählte Entity stellt die für diese Aktion benötigten Kennungen nicht bereit.",
    locked: "Gesperrt",
    unlocked: "Bereit",
    target: "Bewässerungsziel",
    amount: "Menge",
    duration: "Dauer",
    hard_limit: "Maximale Dauer",
    liters: "L",
    seconds: "s",
    maximum: "Maximum",
    start: "Sofort starten",
    invalid_target: "Einen Wert größer als null eingeben.",
    invalid_duration: "Eine gültige positive Dauer eingeben.",
    hard_limit_required: "Eine gültige positive maximale Dauer eingeben.",
    status: "Status",
    amount_mode: "Mengengesteuert",
    duration_mode: "Zeitgesteuert",
    installation: "Bewässerungsanlage",
    physical_meter: "Physischer Zählerstand",
    next_zone: "Nächste Zone",
    expected_start: "Erwarteter Start",
    runtime_today: "Laufzeit heute",
    runtime_month: "Laufzeit diesen Monat",
    water_today: "Gemessenes Wasser heute",
    water_month: "Gemessenes Wasser diesen Monat",
    irrigation_orders: "Bewässerungsaufträge",
    no_open_orders: "Keine offenen Bewässerungsaufträge",
    close: "Schließen",
    loading: "Wird geladen...",
    manual_water: "Manuell bewässern",
    show_history: "Verlauf anzeigen",
    stop_watering: "Bewässerung stoppen",
    confirm_stop_watering: "Die laufende Bewässerung dieser Zone wirklich stoppen?",
    active_execution_choice: "Ein anderer Bewässerungsvorgang ist aktiv",
    stop_active_start_now: "Aktiven Vorgang beenden und sofort starten",
    finish_then_priority: "Aktiven Vorgang abschließen und danach ausführen",
    irrigation_history: "Bewässerungsverlauf",
    source: "Quelle",
    result: "Ergebnis",
    all: "Alle",
    manual: "Manuell",
    automatic: "Automatisch",
    completed: "Abgeschlossen",
    failed: "Fehlgeschlagen",
    cancelled: "Abgebrochen",
    runtime: "Laufzeit",
    water_amount: "Wassermenge",
    pagination: "Seitennavigation des Bewässerungsverlaufs",
    page: "Seite",
    of: "von",
    entries: "Einträge",
    previous: "Zurück",
    next_page: "Weiter",
    date: "Datum",
    today: "Heute",
    previous_day: "Vorheriger Tag",
    next_day: "Nächster Tag",
    no_orders_for_day: "An diesem Tag sind keine Bewässerungsaufträge offen.",
    next_orders_on: "Nächste Aufträge anzeigen am",
    partial_irrigation: "Teilbewässerung",
    portion: "Teilgabe",
    portions: "Teilgaben",
    remaining_target: "Restziel",
    next_portion: "Fortsetzung ab",
    latest_safe_start: "Spätester sicherer Start",
  },
} as const;

export type MessageKey = keyof (typeof messages)["en"];

export function localize(hass: Pick<HomeAssistant, "language">, key: MessageKey): string {
  const language = hass.language?.toLowerCase().startsWith("de") ? "de" : "en";
  return messages[language][key];
}

export function translatedValue(hass: Pick<HomeAssistant, "language">, value: string): string {
  return value in messages.en ? localize(hass, value as MessageKey) : value.replaceAll("_", " ");
}

export function displayState(hass: HomeAssistant, entity?: HassEntity): string {
  if (!entity) return localize(hass, "missing");
  if (entity.state === "unavailable") return localize(hass, "unavailable");
  if (entity.state === "unknown" || entity.state === "") return localize(hass, "unknown");
  if (hass.formatEntityState) return hass.formatEntityState(entity);
  const unit = entity.attributes.unit_of_measurement;
  return `${translatedValue(hass, entity.state)}${unit ? ` ${unit}` : ""}`;
}
